@baseUrl = http://localhost:8080

### Variables
@postId = 69624b15206a5ed5ffa9a551
@commentId = 1
@userId = 5


########POSTS###########
###Create new post
POST {{baseUrl}}/post
Content-Type: application/json

{
  "title": "first post",
  "content": "balaaaaa",
  "sender": {{userId}}
}

###Get all posts
GET {{baseUrl}}/post

###Get post by id
GET {{baseUrl}}/post/{{postId}}

###Get posts by sender id
GET {{baseUrl}}/post?sender={{userId}}

###Update post by id
PUT {{baseUrl}}/post/{{postId}}
Content-Type: application/json

{
  "title": "updated title",
  "content": "mayush",
  "sender": {{userId}}
}

###Delete post by id
DELETE {{baseUrl}}/post/{{postId}}  



#######COMMENTS##########
### Create a new comment
POST {{baseUrl}}/comment
Content-Type: application/json

{
  "postId": {{postId}},
  "sender": {{userId}},
  "content": "a comment"
}

### Get all comment
GET {{baseUrl}}/comment

### Get comment by id
GET {{baseUrl}}/comment/{{commentId}}

### Get comment for a specific post
GET {{baseUrl}}/comment?postId={{postId}}

### Update a comment
PUT {{baseUrl}}/comment/{{commentId}}
Content-Type: application/json

{
  "postId": {{postId}},
  "sender": {{userId}},
  "content": "another comment"
}

### Delete a comment
DELETE {{baseUrl}}/comment/{{commentId}}