@baseUrl = http://localhost:8080

### Variables
@postId = 10
@senderId = 10
@commentId = 1
@userId = 5


########POSTS###########
###Create new post
POST {{baseUrl}}/post
Content-Type: application/json
{
  "title": "first post",
  "body": "karenush",
  "sender": {{senderId}}
}

###Get all posts
GET {{baseUrl}}/post

###Get post by id
GET {{baseUrl}}/post/{{postId}}

###Get posts by sender id
GET {{baseUrl}}/post?sender={{senderId}}

###Update post by id
PUT {{baseUrl}}/post/{{postId}}
Content-Type: application/json
{
  "title": "updated title",
  "body": "mayush",
  "sender": {{senderId}}
}



#######COMMENTS##########
### Create a new comment
POST {{baseUrl}}/comment
Content-Type: application/json
{
  "postId": {{postId}},
  "userId": {{userId}},
  "text": "a comment"
}

### Get all comment
GET {{baseUrl}}/comment

### Get comment by id
GET {{baseUrl}}/comment/{{commentId}}

### Get comment for a specific post
GET {{baseUrl}}/comment?postId={{postId}}

### Update a comment
PUT {{baseUrl}}/comment/{{commentId}}
Content-Type: application/json
{
  "postId": {{postId}},
  "userId": {{userId}},
  "text": "another comment"
}

# Delete a comment
DELETE {{baseUrl}}/comment/{{commentId}}